export const ROUTES = {
  home: "/",
  chat: (chatId: string) => `/c/${chatId}`,
  settings: "/settings",
  settingsProfile: "/settings/profile",
  settingsAppearance: "/settings/appearance",
  settingsModels: "/settings/models",
  settingsApiKeys: "/settings/api-keys",
  settingsHistory: "/settings/history",
  settingsMemory: "/settings/memory",
  settingsNotifications: "/settings/notifications",
  settingsPrivacy: "/settings/privacy",
  settingsSubscription: "/settings/subscription",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
} as const;
